Unfreeze pluggy version (#79)
* Unfreeze pluggy version

pytest 2.9 requires pluggy>=0.7

By fixing pluggy we broke pytest.

This fixes failure on python TypeError: __call__() got an unexpected keyword argument 'warn_on_impl'