fix: setup unaccent extension drop
in some cases, the DROP EXTENSION can fail because there are elements depending on it:

ERROR:  cannot drop extension unaccent because other objects depend on it
DETAIL:  function unaccent(text) depends on text search dictionary unaccent_schema.unaccent
HINT:  Use DROP ... CASCADE to drop the dependent objects too.